# Generated by Django 5.1 on 2024-08-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.ImageField(default='posts/default.jpg', upload_to='images/'),
        ),
    ]
