# Generated by Django 5.1 on 2024-08-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.ImageField(blank=True, default='posts/default.jpg', null=True, upload_to='images/'),
        ),
    ]
