# Generated by Django 5.1 on 2024-08-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_delete_image_alter_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
